language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php:
        - hhvm
        - nightly
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
script:
  - composer require codeclimate/php-test-reporter --dev
  - echo "Running PHPUnit Tests"
  - phpunit --coverage-clover build/logs/clover.xml tests
after_script:
  - vendor/bin/test-reporter
